# Get mac address table


- name: Get MAC address table from Cisco Nexus devices
  hosts: all
  gather_facts: no
  connection: ansible.netcommon.network_cli
  vars:
    tmp_folder: "./tmp"
    output_file: "output/mac_address_table_nexus.csv"
  vars_files:
    - "credentials.yml"  
  tasks:
    - name: Deleting tmp dir
      file: path="{{ tmp_folder }}" state=absent
      delegate_to: localhost
      run_once: true

    - name: Creating tmp dir
      file: path="{{ tmp_folder }}" state=directory
      delegate_to: localhost
      run_once: true

    - name: Get MAC address table from devices
      ansible.utils.cli_parse:
        command: "show mac address-table"
        parser:
          name: ansible.utils.textfsm
          template_path: templates/nxos_show_mac_address-table.textfsm
        set_fact: mac_address_table

    - name: Save partial outputs
      ansible.builtin.lineinfile:
        create: yes
        mode: '0660'
        line: "{{ inventory_hostname }};{{ item.VLAN_ID }};{{ item.MAC_ADDRESS }};{{ item.TYPE }};{{ item.PORT }}"
        path: "{{ tmp_folder }}/{{ inventory_hostname }}.txt"
      loop: "{{ mac_address_table }}"
      delegate_to: localhost

    - name: Generate output log
      ansible.builtin.assemble:
        src: "{{ tmp_folder }}"
        dest: "{{ output_file }}"
      delegate_to: localhost  
      run_once: true

    - name: Create header in output file
      lineinfile:
        path: "{{ output_file }}"
        insertbefore: BOF
        line: "HOSTNAME;VLAN_ID;MAC_ADDRESS;TYPE;PORT;"

    - name: Deleting temp dir
      file: path="{{ tmp_folder }}" state=absent
      delegate_to: localhost
      run_once: true 
