---
# Get interfaces switchport status


- name: Get interfaces switchport status
  hosts: all
  gather_facts: no
  connection: ansible.netcommon.network_cli
  vars:
    tmp_folder: "./tmp"
    output_file: "output/ifswitchport.csv"
  vars_files:
    - "credentials.yml"  
  tasks:
    - name: Deleting tmp dir
      file: path="{{ tmp_folder }}" state=absent
      delegate_to: localhost
      run_once: true

    - name: Creating tmp dir
      file: path="{{ tmp_folder }}" state=directory
      delegate_to: localhost
      run_once: true

    - name: Get if switchport state from devices
      ansible.utils.cli_parse:
        command: "show interfaces switchport"
        parser:
          name: ansible.utils.textfsm
          template_path: templates/ios_show_if_switchport.textfsm
        set_fact: if_switchport

    - name: Save partial outputs
      ansible.builtin.lineinfile:
        create: yes
        mode: '0660'
        line: "{{ inventory_hostname }};{{ item.IFNAME }};{{ item.SWITCHPORT }};{{ item.ADMIN_MODE }};{{ item.OPER_MODE }};{{ item.ADMIN_TRUNK }};{{ item.OPER_TRUNK }};{{ item.ACCESS_MODE_VLAN }};{{ item.NATIVE_VLAN }};{{ item.PRIV_VLAN }};{{ item.TRUNK_VLAN }}"
        path: "{{ tmp_folder }}/{{ inventory_hostname }}.txt"  
      loop: "{{ if_switchport }}"  
      delegate_to: localhost

    - name: Generate output log
      ansible.builtin.assemble:
        src: "{{ tmp_folder }}"
        dest: "{{ output_file }}"
      delegate_to: localhost  
      run_once: true
    
    - name: Deleting temp dir
      file: path="{{ tmp_folder }}" state=absent
      delegate_to: localhost
      run_once: true 
      
      
   