---
# Get interfaces poe status


- name: Get interfaces poe
  hosts: all
  gather_facts: no
  connection: ansible.netcommon.network_cli
  vars:
    tmp_folder: "./tmp"
    output_file: "output/ifpoe.csv"
  vars_files:
    - "credentials.yml"  
  tasks:
    - name: Deleting tmp dir
      file: path="{{ tmp_folder }}" state=absent
      delegate_to: localhost
      run_once: true

    - name: Creating tmp dir
      file: path="{{ tmp_folder }}" state=directory
      delegate_to: localhost
      run_once: true

    - name: Get if poe capabilites from devices
      ansible.utils.cli_parse:
        command: "show power inline"
        parser:
          name: ansible.utils.textfsm
          template_path: templates/ios_show_power_inline.textfsm
        set_fact: if_poe

    - name: Save partial outputs
      ansible.builtin.lineinfile:
        create: yes
        mode: '0660'
        line: "{{ inventory_hostname }};{{ item.IFNAME }};{{ item.ADMIN }};{{ item.OPER }};{{ item.POWER }};{{ item.DEVICE }};{{ item.CLASS }};{{ item.MAX }}"
        path: "{{ tmp_folder }}/{{ inventory_hostname }}.txt"  
      loop: "{{ if_poe }}"  
      delegate_to: localhost

    - name: Generate output log
      ansible.builtin.assemble:
        src: "{{ tmp_folder }}"
        dest: "{{ output_file }}"
      delegate_to: localhost  
      run_once: true
    
    - name: Deleting temp dir
      file: path="{{ tmp_folder }}" state=absent
      delegate_to: localhost
      run_once: true 
      
      
   