---
# Get switch stack status


- name: Get switch stack status
  hosts: all
  gather_facts: no
  connection: ansible.netcommon.network_cli
  vars:
    tmp_folder: "./tmp"
    output_file: "output/sw_stack.csv"
  vars_files:
    - "credentials.yml"  
  tasks:
    - name: Deleting tmp dir
      file: path="{{ tmp_folder }}" state=absent
      delegate_to: localhost
      run_once: true

    - name: Creating tmp dir
      file: path="{{ tmp_folder }}" state=directory
      delegate_to: localhost
      run_once: true

    - name: Get switch stack info
      ansible.utils.cli_parse:
        command: "show switch"
        parser:
          name: ansible.utils.textfsm
          template_path: templates/ios_show_switch.textfsm
        set_fact: sw_stack

    - name: Save partial outputs
      ansible.builtin.lineinfile:
        create: yes
        mode: '0660'
        line: "{{ inventory_hostname }};{{ item.SWITCH_NUM }};{{ item.MAC }};{{ item.PRIORITY }};{{ item.HW_VER }};{{ item.STATE }}"
        path: "{{ tmp_folder }}/{{ inventory_hostname }}.txt"  
      loop: "{{ sw_stack }}"  
      delegate_to: localhost

    - name: Generate output log
      ansible.builtin.assemble:
        src: "{{ tmp_folder }}"
        dest: "{{ output_file }}"
      delegate_to: localhost  
      run_once: true
    
    - name: Deleting temp dir
      file: path="{{ tmp_folder }}" state=absent
      delegate_to: localhost
      run_once: true 
      
      
   